import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';

import '../../model/plan/total_plan.dart';
import '../../model/record/day_record.dart';
import '../../model/record/monthly_record.dart';
import '../../repository/auth_repository.dart';
import '../../repository/plan_repository.dart';
import '../../repository/record_repository.dart';

class PendingSpendingViewModel extends ChangeNotifier {
  PendingSpendingViewModel(
      this._authRepo,
      this._planRepo,
      this._recordRepo,
      );

  final AuthRepository _authRepo;
  final PlanRepository _planRepo;
  final RecordRepository _recordRepo;

  bool _isLoading = false;
  String? _error;

  bool get isLoading => _isLoading;
  String? get error => _error;

  String _userName = '회원';
  String get userName => _userName;

  TotalPlan? _latestPlan;

  DateTime? _initialMonth;
  DateTime? get initialMonth => _initialMonth;

  DateTime? _selectedPendingDate;
  DateTime? get selectedPendingDate => _selectedPendingDate;

  final Map<String, MonthlyRecord> _monthlyCache = {};

  final Set<DateTime> _recordedDates = {};
  final Set<DateTime> _pendingDates = {};

  List<DateTime> get recordedDates =>
      _recordedDates.toList()..sort((a, b) => a.compareTo(b));

  List<DateTime> get pendingDates =>
      _pendingDates.toList()..sort((a, b) => a.compareTo(b));

  int get pendingDayCount => _pendingDates.length;

  String get dailyLimitText {
    final metrics = _latestPlan?.result.totalMetrics;
    if (metrics == null) return '—';
    final value = metrics.dailyConsumeAmount.toDouble();
    return '${NumberFormat('#,###').format(value)}원';
  }

  DateTime get _today {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day);
  }

  DateTime _normalize(DateTime d) => DateTime(d.year, d.month, d.day);

  String _monthKey(DateTime d) => DateFormat('yyyy-MM').format(d);
  String _dateKey(DateTime d) => DateFormat('yyyy-MM-dd').format(d);

  DateTime? get _planStartDate {
    final raw = _latestPlan?.startDate ?? _latestPlan?.creationDate;
    if (raw == null) return null;
    return _normalize(raw);
  }

  Future<void> load({DateTime? initialMonth, bool forceRefresh = false}) async {
    if (_isLoading) return;
    if (!forceRefresh && _initialMonth == initialMonth && _pendingDates.isNotEmpty) {
      return;
    }

    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _userName = await _authRepo.getUserName();
      _latestPlan = await _planRepo.getLatestPlanForCurrentUser();

      final today = _today;
      final start = _planStartDate;

      _initialMonth = _clampMonth(initialMonth ?? today);

      _monthlyCache.clear();
      _recordedDates.clear();
      _pendingDates.clear();
      _selectedPendingDate = null;

      if (start != null && !start.isAfter(today)) {
        await _loadMonthsInRange(start, today);
        _buildCalendarSets(start: start, end: today);
      }
    } catch (e) {
      _error = e.toString();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  DateTime _clampMonth(DateTime date) {
    final normalized = _normalize(date);
    final today = _today;
    final start = _planStartDate;

    if (normalized.isAfter(today)) return today;
    if (start != null && normalized.isBefore(start)) return start;
    return normalized;
  }

  Future<void> _loadMonthsInRange(DateTime start, DateTime end) async {
    var cursor = DateTime(start.year, start.month, 1);
    final last = DateTime(end.year, end.month, 1);

    while (!cursor.isAfter(last)) {
      final key = _monthKey(cursor);
      final monthly = await _recordRepo.loadMonthlyRecord(key);
      _monthlyCache[key] = monthly;
      cursor = DateTime(cursor.year, cursor.month + 1, 1);
    }
  }

  void _buildCalendarSets({
    required DateTime start,
    required DateTime end,
  }) {
    var cursor = start;

    while (!cursor.isAfter(end)) {
      final normalized = _normalize(cursor);
      final day = _findDayRecord(normalized);

      if (_isRecordedDay(day)) {
        _recordedDates.add(normalized);
      } else {
        _pendingDates.add(normalized);
      }

      cursor = cursor.add(const Duration(days: 1));
    }
  }

  DayRecord? _findDayRecord(DateTime date) {
    final monthly = _monthlyCache[_monthKey(date)];
    return monthly?.days[_dateKey(date)];
  }

  bool _isRecordedDay(DayRecord? day) {
    if (day == null) return false;
    if (day.isAutoGenerated) return false;

    final hasSpending =
        day.totalSpendingAmount > 0 || day.spendingEntries.isNotEmpty;

    return hasSpending;
  }

  bool isPendingDay(DateTime date) {
    final normalized = _normalize(date);
    return _pendingDates.contains(normalized);
  }

  void selectPendingDate(DateTime date) {
    final normalized = _normalize(date);
    if (!isPendingDay(normalized)) return;

    _selectedPendingDate = normalized;
    notifyListeners();
  }

  void clearSelectedPendingDate() {
    _selectedPendingDate = null;
    notifyListeners();
  }
}