enum ChatStep {
  greeting,
  onboarding1,
  onboarding2,
  onboarding3,
  planName,
  purpose,
  purposeCustom,
  targetAmount,
  currentAsset,
  monthlyIncome,
  monthlyFixedCost,
  dailySpending,
  summaryIntro,
  summary,
  autoService,
  complete,
}