// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ212nyxSbezNMEbVZ4tNOT0bx6GHP1tI',
    appId: '1:355560484884:web:fa5695e554b68442763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    authDomain: 'sotong-db.firebaseapp.com',
    storageBucket: 'sotong-db.firebasestorage.app',
    measurementId: 'G-DTWWKGS5V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMYdXrOAKJKn57F4cJIoTE590D3-4Rhk',
    appId: '1:355560484884:android:7436467d863e05d8763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    storageBucket: 'sotong-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysRLq2HlsB-2ZeaxpiilA8QeGwMwWSAU',
    appId: '1:355560484884:ios:359f36a37f31cd7c763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    storageBucket: 'sotong-db.firebasestorage.app',
    iosBundleId: 'com.example.sotongLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBysRLq2HlsB-2ZeaxpiilA8QeGwMwWSAU',
    appId: '1:355560484884:ios:359f36a37f31cd7c763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    storageBucket: 'sotong-db.firebasestorage.app',
    iosBundleId: 'com.example.sotongLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ212nyxSbezNMEbVZ4tNOT0bx6GHP1tI',
    appId: '1:355560484884:web:014d7af259fa7d62763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    authDomain: 'sotong-db.firebaseapp.com',
    storageBucket: 'sotong-db.firebasestorage.app',
    measurementId: 'G-Z94LRMHK42',
  );
}
