// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ212nyxSbezNMEbVZ4tNOT0bx6GHP1tI',
    appId: '1:355560484884:web:fa5695e554b68442763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    authDomain: 'sotong-db.firebaseapp.com',
    storageBucket: 'sotong-db.firebasestorage.app',
    measurementId: 'G-DTWWKGS5V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaH88k55rAQkiZCFNyTZ8hzMnrsu8HKgs',
    appId: '1:421086465432:android:53ac68e554a9a04d476fed',
    messagingSenderId: '421086465432',
    projectId: 'sotongmoneymanageapp',
    storageBucket: 'sotongmoneymanageapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7trDtAPJR3BCmdO1wupqmFPSTTgLpPms',
    appId: '1:421086465432:ios:80d560226c019763476fed',
    messagingSenderId: '421086465432',
    projectId: 'sotongmoneymanageapp',
    storageBucket: 'sotongmoneymanageapp.firebasestorage.app',
    iosBundleId: 'com.example.sotong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7trDtAPJR3BCmdO1wupqmFPSTTgLpPms',
    appId: '1:421086465432:ios:80d560226c019763476fed',
    messagingSenderId: '421086465432',
    projectId: 'sotongmoneymanageapp',
    storageBucket: 'sotongmoneymanageapp.firebasestorage.app',
    iosBundleId: 'com.example.sotong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ212nyxSbezNMEbVZ4tNOT0bx6GHP1tI',
    appId: '1:355560484884:web:014d7af259fa7d62763701',
    messagingSenderId: '355560484884',
    projectId: 'sotong-db',
    authDomain: 'sotong-db.firebaseapp.com',
    storageBucket: 'sotong-db.firebasestorage.app',
    measurementId: 'G-Z94LRMHK42',
  );
}